In [253]:
import numpy as np
from math import exp



In [254]:
class SigmoidLayer():
    def __init__(self):
        self.gradInput = None
        self.params = None
        """
        На будущее необходимо сохранить параметры и gradInput
        """



    def forward(self, X):
        """
        Реализовать forward pass
        P.S. не забудьте сохранить X во внутреннюю переменную
        """
        self.X = X.copy()
        sigmoid = X.copy()
        for ind1, i in enumerate(X):
            for ind2, j in enumerate(i):
                sigmoid[ind1][ind2] = 1/(1 + exp(-j))
        return  sigmoid

In [255]:
np.random.seed(17)

X = np.random.random(size=(100, 3))
sigmoid = SigmoidLayer()
output = sigmoid.forward(X)

correct_answer = np.array([[0.57313782, 0.62961995, 0.54773438],
                           [0.51696857, 0.68718368, 0.65843628],
                           [0.65419284, 0.64005501, 0.50976449],
                           [0.58851107, 0.7202462 , 0.51500666],
                           [0.70350447, 0.70626044, 0.51279562]])
assert np.isclose(output[:5], correct_answer).all()
assert hasattr(sigmoid, "params"), "Нет параметра params в реализованном классе"
assert hasattr(sigmoid, "gradInput"), "Нет параметра gradInput в реализованном классе"
assert hasattr(sigmoid, "X"), "Не сохранили X в реализованном классе"

In [256]:
class TanhLayer():
    def __init__(self):
        """
        На будущее необходимо сохранить параметры и gradInput
        """
        self.gradInput = None
        self.params = None


    def forward(self, X):
        """
        Реализовать forward pass
        P.S. не забудьте сохранить X во внутреннюю переменную
        """
        self.X = X.copy()
        tanh = X.copy()
        for ind1, i in enumerate(X):
            for ind2, j in enumerate(i):
                tanh[ind1][ind2] = (exp(j) - exp(-j))/(exp(j) + exp(-j))

        return  tanh

In [257]:
np.random.seed(17)

X = np.random.random(size=(100, 3))
tanh = TanhLayer()
output = tanh.forward(X)
correct_answer = np.array([[0.28642281, 0.48582948, 0.18921297],
                           [0.0677962 , 0.65669792, 0.57591821],
                           [0.5632092 , 0.51946218, 0.03904306],
                           [0.34328675, 0.73782249, 0.05997262],
                           [0.69833441, 0.70505935, 0.05114899]])
assert np.isclose(output[:5], correct_answer).all()
assert hasattr(tanh, "params"), "Нет параметра params в реализованном классе"
assert hasattr(tanh, "gradInput"), "Нет параметра gradInput в реализованном классе"
assert hasattr(tanh, "X"), "Не сохранили X в реализованном классе"

In [258]:
class MSELoss():
    def forward(self, y_true, y_pred):
        """
        Реализовать forward pass
        """
        self.yt = y_true.copy()
        self.yp = y_pred.copy()
        l = len(y_true)
        self.mse = 0
        for i in range(l):
            self.mse += (self.yt[i] - self.yp[i]) ** 2
        return self.mse/l

In [259]:
np.random.seed(17)

y_true = np.random.randint(0, 1000, size=(100))
y_pred = np.random.randint(0, 1000, size=(100))
mse = MSELoss()
output = mse.forward(y_true, y_pred)
correct_answer = 157953.51
assert round(output, 2) == round(correct_answer, 2)

In [260]:
class LinearLayer:
    """
    Линейный слой с семинаров, ничего менять не надо
    """
    def __init__(self, in_size, out_size):
        self.W = np.random.randn(in_size, out_size)
        self.params = [self.W]
        self.gradW = None
        self.gradInput = None

    def forward(self, X):
        self.X = X.copy()
        output = X.dot(self.W)
        return output


class NN:
    def __init__(self, loss_func):
        """
        Необходимо, чтобы нейросеть знала все о своей конфигурации.
        1. Создайте внутренние переменные layers, params и grads как пустые листы.
        2. Во внутреннюю переменную loss_func положите значение полученной переменной loss_func.
        """
        self.layers = []
        self.params = []
        self.grads = []
        self.loss_func = loss_func

    def add_layer(self, layer):
        """
        Функция добавления слоев в нейросеть.
        Необходимо, чтобы обновлялись (расширялись) внутренние переменные,
        ответственные за слои и параметры этих самых слоев, которые мы инициализировали
        в __init__ методе.
        """
        self.layers.append(layer)


    def forward(self, X):
        """
        Реализовать forward pass для всей нейросети.
        Т.е. реализовать forward pass по каждому слою, и в конце выдать результат
        """

        for i in self.layers:
            output = i.forward(X)
            X = output
            print(output)
            print("\n\n\n\n")

        return output

In [261]:
nn = NN(MSELoss())

assert hasattr(nn, "layers")
assert hasattr(nn, "params")
assert hasattr(nn, "grads")
assert hasattr(nn, "loss_func")
assert isinstance(nn.loss_func, MSELoss)

In [262]:
np.random.seed(17)

X = np.random.random(size=(100, 3))
nn = NN(MSELoss())

linear1 = LinearLayer(3, 5)
nn.add_layer(linear1)

sigmoid1 = SigmoidLayer()
nn.add_layer(sigmoid1)

linear2 = LinearLayer(5, 1)
nn.add_layer(linear2)

sigmoid2 = SigmoidLayer()
nn.add_layer(sigmoid2)

output_nn = nn.forward(X)

assert round(output_nn.sum()) == 65

[[-7.34214336e-02  2.19697695e-01  9.21561730e-01 -1.11175540e-02
  -8.94952944e-01]
 [-2.30342032e-01  3.77309638e-01  1.69801687e+00 -6.83171591e-01
  -3.69285684e-01]
 [ 2.61724922e-02  2.55024870e-01  9.99705323e-01  4.79290273e-01
  -1.73875690e+00]
 [-1.89655868e-01  2.34106493e-01  9.47562736e-01 -7.69717975e-02
  -1.33000137e+00]
 [ 3.51783492e-03  3.56744223e-01  1.40077543e+00  5.99788452e-01
  -2.41472330e+00]
 [ 4.36690767e-02  4.80402957e-01  2.05103606e+00  2.06341609e-01
  -1.54757312e+00]
 [ 7.25564955e-02  2.82451114e-01  1.18393734e+00  2.97732375e-01
  -1.12702250e+00]
 [ 6.57692971e-02  5.14123742e-01  2.24067703e+00  6.92979513e-02
  -1.18204134e+00]
 [ 9.51159494e-02  1.89293544e-01  7.73114239e-01  3.68592031e-01
  -9.55802085e-01]
 [-2.14966941e-01  2.19349805e-01  9.67053301e-01 -4.64825010e-01
  -4.37369788e-01]
 [-2.01514727e-01  3.81989900e-01  1.68499580e+00 -4.93762256e-01
  -7.18813307e-01]
 [-1.50052319e-01  1.51955068e-01  6.56144603e-01 -2.67757579e-01

In [263]:
np.random.seed(17)

nn = NN(MSELoss())

linear1 = LinearLayer(4, 4)
nn.add_layer(linear1)

sigmoid1 = SigmoidLayer()
nn.add_layer(sigmoid1)

linear2 = LinearLayer(4, 5)
nn.add_layer(linear2)

tanh2 = TanhLayer()
nn.add_layer(tanh2)

linear3 = LinearLayer(5, 6)
nn.add_layer(linear3)

sigmoid3 = SigmoidLayer()
nn.add_layer(sigmoid3)

linear4 = LinearLayer(6, 4)
nn.add_layer(linear4)

sigmoid4 = SigmoidLayer()
nn.add_layer(sigmoid4)

linear5 = LinearLayer(4, 3)
nn.add_layer(linear5)

tanh5 = TanhLayer()
nn.add_layer(tanh5)

linear6 = LinearLayer(3, 3)
nn.add_layer(linear6)

sigmoid6 = SigmoidLayer()
nn.add_layer(sigmoid6)


In [264]:
np.random.seed(17)
X = np.random.randn(100, 4)
output = nn.forward(X)

assert output.shape == (100, 3)

layer_weights = []
for layer in nn.layers:
    if isinstance(layer, LinearLayer):
        layer_weights.append(layer.W.shape)
right_weights = [(4, 4), (4, 5), (5, 6), (6, 4), (4, 3), (3, 3)]
assert layer_weights == right_weights

[[-3.83762750e+00 -4.44262687e+00  2.35245544e+00 -3.26349447e-01]
 [ 2.88533190e+00  1.73469137e+00 -1.63239751e-03  1.01887248e+00]
 [-2.18601504e+00 -2.21129106e+00  5.47807783e+00  7.85086791e-01]
 [ 2.66350674e+00  3.12151504e+00 -9.05576330e-01  1.74057146e+00]
 [ 1.64565401e-01 -2.81915649e+00 -1.63325026e+00  8.62660690e-01]
 [ 1.68366349e+00  3.61398463e+00  9.76488659e-02 -1.39363923e-01]
 [-5.57890905e-01  2.25190472e+00 -3.06416184e+00 -2.65234006e+00]
 [ 5.51663052e-01  1.65196554e+00  1.53741331e+00  3.80796059e-01]
 [-1.09727250e+00 -1.69423034e-01  2.60290048e+00 -4.18051534e-01]
 [ 4.16927607e+00  6.16041765e-01 -3.32716585e+00  2.75340316e+00]
 [ 4.43178640e+00  8.49431801e+00 -1.19409992e+00 -1.15620130e+00]
 [-9.27082348e-01 -1.22356212e+00  2.10152786e+00  8.96786369e-02]
 [ 8.86675626e-01 -1.38114707e-01  1.41540004e+00  2.27085532e+00]
 [-1.92375805e+00 -1.84867865e+00  1.58120144e+00 -4.31817235e-01]
 [ 2.37599206e+00  3.78690825e+00 -2.47811865e+00 -5.60333521e